// RemoteAccessIdentity.swift — Packet E (PRJCT-2754 · durable Remote-Access config)
// TheBridge · Modules · Auth
//
// ⚠️ GENERATED / BUILD-INJECTED — do not hand-edit.
//
// The operator's WorkOS/OAuth IdP identity, baked into the binary at build time
// (same pattern as LicensePublicKeyInjected.swift, Packet B) so it is present at
// EVERY launch with NO dependency on launchctl-setenv timing — the root cause of
// the placeholder-PRM revert this packet fixes. Regenerated by
// `make inject-remote-access` (scripts/inject-remote-access.sh): a no-op locally
// when no identity is in the environment (leaves the fail-closed default),
// release.yml bakes from repo secrets, or an explicit
// `make build BRIDGE_OAUTH_ISSUER=… WORKOS_CLIENT_ID=…` bakes those values.
//
// Committed defaults are EMPTY = fail-closed: an unbaked build resolves to the
// documented placeholder issuer and is reported `.misconfigured` (Wave 3) rather
// than silently advertising a wrong authorization server. All values are
// NON-SECRET (public issuer / clientID / redirect / resource); the WorkOS client
// secret is never here — the Bridge is an OAuth resource server, not a
// confidential client.

enum RemoteAccessIdentity {
    static let issuer = ""             // INJECT:BRIDGE_OAUTH_ISSUER
    static let publicResource = ""     // INJECT:BRIDGE_PUBLIC_RESOURCE
    static let workosClientID = ""     // INJECT:WORKOS_CLIENT_ID
    static let workosBaseURL = ""      // INJECT:WORKOS_BASE_URL
    static let workosRedirectURI = ""  // INJECT:WORKOS_REDIRECT_URI
}
